name: Guard API Key Leak
on: push

jobs:
  detect-key-leak:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: yarn build
      run: yarn && yarn build
      working-directory: ./generator/konfig-dash
      env:
        # required to avoid `Usage Error: Environment variable not found (NPM_TOKEN)`
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: sanity check script
      run: cat ./guard-api-key-leak.sh
      working-directory: ./generator/konfig-dash/bash-scripts

    - name: Detect API key leaks
      run: ./guard-api-key-leak.sh
      working-directory: ./generator/konfig-dash/bash-scripts
