name: Guard API Key Leak
on: [push, pull_request]

jobs:
  detect-key-leak:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Make script executable
      run: chmod +x guard-api-key-leak.sh
      working-directory: generator/konfig-dash/bash_scripts

    - name: Detect API key leaks
      run: ./guard-api-key-leak.sh
      working-directory: generator/konfig-dash/bash_scripts
