name: Custom Action Workflow

on:
  push:
    branches:
      - main # Change this to the desired branch name

jobs:
  run-custom-action:
    runs-on: ubuntu-latest
    
    steps:

    - name: Start
      run: echo "Start"

    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run Custom Action
      uses: konfig-dev/konfig/.github/actions/merge-pull-request@test-custom-action
      with:
        pr_number: 123
        merge_method: squash

    - name: End
      run: echo "End"